name: SDET Framework Tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t my-sdet-framework .

    # Step: Container ko naam dekar run karna taaki hum baad mein files nikaal sakein
    - name: Run Tests in Docker
      run: |
        docker run --name test-container my-sdet-framework || true

    # Step: Container ke andar se Reports aur Screenshots local machine par lana
    - name: Copy Artifacts from Container
      if: always()
      run: |
        docker cp test-container:/app/target/surefire-reports ./target/surefire-reports || echo "Reports not found"
        docker cp test-container:/app/Screenshots ./Screenshots || echo "Screenshots not found"

    # Step: Ab ye local folders ko upload karega
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: automation-execution-results
        path: |
          target/surefire-reports/
          Screenshots/